-- MySQL Script generated by MySQL Workbench
-- Tue Jan 10 18:53:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hangar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hangar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hangar` DEFAULT CHARACTER SET utf8mb4 ;
USE `hangar` ;

-- -----------------------------------------------------
-- Table `hangar`.`carritoCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar`.`carritoCompra` (
  `id_carritoCompra` INT NOT NULL AUTO_INCREMENT,
  `agregarProducto` VARCHAR(45) NOT NULL,
  `vaciarCarrito` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `cantidadProducto` TINYINT(20) NOT NULL,
  `producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_carritoCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar`.`pedidos` (
  `id_pedidos` INT NOT NULL,
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  `fechaCompra` DATE NULL,
  `direccionEntrega` VARCHAR(45) NOT NULL,
  `recargoEnvio` FLOAT NULL,
  `descuento` FLOAT NULL,
  `totalPago` FLOAT NOT NULL,
  `verPedido` LONGBLOB NOT NULL,
  `modificarPedido` VARCHAR(45) NULL,
  `eliminarPedido` VARCHAR(45) NULL,
  `id_carritoCompra` INT NOT NULL,
  `id_roles` INT NOT NULL,
  INDEX `id_carritoCompra_idx` (`id_carritoCompra` ASC),
  PRIMARY KEY (`id_pedidos`),
  CONSTRAINT `id_carritoCompra`
    FOREIGN KEY (`id_carritoCompra`)
    REFERENCES `hangar`.`carritoCompra` (`id_carritoCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `id_productos` INT NOT NULL,
  `id_mediosDePago` INT NOT NULL,
  `id_pedidos` INT NOT NULL,
  INDEX `id_pedidos_idx` (`id_pedidos` ASC),
  PRIMARY KEY (`id_ventas`),
  CONSTRAINT `id_pedidos`
    FOREIGN KEY (`id_pedidos`)
    REFERENCES `hangar`.`pedidos` (`id_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `celular` FLOAT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `image` LONGBLOB NOT NULL,
  `id_roles` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  INDEX `id_roles_idx` (`id_roles` ASC),
  CONSTRAINT `id_roles`
    FOREIGN KEY (`id_roles`)
    REFERENCES `hangar`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar`.`roles` (
  `id_roles` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(45) NOT NULL,
  `administrador` VARCHAR(45) NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  `vendedor` VARCHAR(45) NOT NULL,
  `id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_roles`),
  INDEX `id_usuarios_idx` (`id_usuarios` ASC),
  CONSTRAINT `id_usuarios`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `hangar`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar`.`productos` (
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  `articuloProducto` VARCHAR(45) NOT NULL,
  `descripcionProducto` VARCHAR(45) NOT NULL,
  `imageProducto` LONGBLOB NULL,
  `precio` FLOAT NOT NULL,
  `altaProducto` DATE NOT NULL,
  `modificarProducto` DATE NULL,
  `eliminarProducto` VARCHAR(45) NULL,
  `listarProducto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_productos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar`.`mediosDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar`.`mediosDePago` (
  `id_mediosDePago` INT NOT NULL AUTO_INCREMENT,
  `tarjetaDeCredito` TINYINT(30) NOT NULL,
  `transferencia` TINYINT(30) NOT NULL,
  `billetera` TINYINT(30) NOT NULL,
  `mercadoLibre` TINYINT(30) NOT NULL,
  `id_ventas` INT NOT NULL,
  INDEX `id_ventas_idx` (`id_ventas` ASC),
  PRIMARY KEY (`id_mediosDePago`),
  CONSTRAINT `id_ventas`
    FOREIGN KEY (`id_ventas`)
    REFERENCES `hangar`.`ventas` (`id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
